In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("players_season.csv")
df

,Unnamed: 0,Name,From,To,Height,Weight,Age,Tm,Lg,Pos,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,abdulta01 1998,Tariq Abdul-Wahad,1998,2003,6-6,223.0,23.0,SAC,NBA,SG,...,0.672,0.7,1.2,2.0,0.9,0.6,0.2,1.1,1.4,6.4
1,abdulta01 1999,Tariq Abdul-Wahad,1998,2003,6-6,223.0,24.0,SAC,NBA,SG,...,0.691,1.5,2.3,3.8,1.0,1.0,0.3,1.4,2.5,9.3
2,abdulta01 2000,Tariq Abdul-Wahad,1998,2003,6-6,223.0,25.0,TOT,NBA,SG,...,0.756,1.7,3.1,4.8,1.6,1.0,0.5,1.7,2.4,11.4
3,abdulta01 2001,Tariq Abdul-Wahad,1998,2003,6-6,223.0,26.0,DEN,NBA,SG,...,0.583,0.5,1.6,2.0,0.8,0.5,0.4,1.2,1.9,3.8
4,abdulta01 2002,Tariq Abdul-Wahad,1998,2003,6-6,223.0,27.0,TOT,NBA,SG,...,0.727,1.7,1.8,3.5,1.0,0.8,0.4,1.1,2.3,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24687,zubaciv01 2018,Ivica Zubac,2017,2022,7-0,240.0,20.0,LAL,NBA,C,...,0.765,1.0,1.8,2.9,0.6,0.2,0.3,0.6,1.1,3.7
24688,zubaciv01 2019,Ivica Zubac,2017,2022,7-0,240.0,21.0,TOT,NBA,C,...,0.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
24689,zubaciv01 2020,Ivica Zubac,2017,2022,7-0,240.0,22.0,LAC,NBA,C,...,0.747,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3
24690,zubaciv01 2021,Ivica Zubac,2017,2022,7-0,240.0,23.0,LAC,NBA,C,...,0.789,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0
24691,zubaciv01 2022,Ivica Zubac,2017,2022,7-0,240.0,24.0,LAC,NBA,C,...,0.735,2.6,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6

In [4]:
df[['id', 'Year']] = df['Unnamed: 0'].str.split(" ", n=2, expand=True)
df

,Unnamed: 0,Name,From,To,Height,Weight,Age,Tm,Lg,Pos,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,id,Year
0,abdulta01 1998,Tariq Abdul-Wahad,1998,2003,6-6,223.0,23.0,SAC,NBA,SG,...,1.2,2.0,0.9,0.6,0.2,1.1,1.4,6.4,abdulta01,1998
1,abdulta01 1999,Tariq Abdul-Wahad,1998,2003,6-6,223.0,24.0,SAC,NBA,SG,...,2.3,3.8,1.0,1.0,0.3,1.4,2.5,9.3,abdulta01,1999
2,abdulta01 2000,Tariq Abdul-Wahad,1998,2003,6-6,223.0,25.0,TOT,NBA,SG,...,3.1,4.8,1.6,1.0,0.5,1.7,2.4,11.4,abdulta01,2000
3,abdulta01 2001,Tariq Abdul-Wahad,1998,2003,6-6,223.0,26.0,DEN,NBA,SG,...,1.6,2.0,0.8,0.5,0.4,1.2,1.9,3.8,abdulta01,2001
4,abdulta01 2002,Tariq Abdul-Wahad,1998,2003,6-6,223.0,27.0,TOT,NBA,SG,...,1.8,3.5,1.0,0.8,0.4,1.1,2.3,5.6,abdulta01,2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24687,zubaciv01 2018,Ivica Zubac,2017,2022,7-0,240.0,20.0,LAL,NBA,C,...,1.8,2.9,0.6,0.2,0.3,0.6,1.1,3.7,zubaciv01,2018
24688,zubaciv01 2019,Ivica Zubac,2017,2022,7-0,240.0,21.0,TOT,NBA,C,...,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,zubaciv01,2019
24689,zubaciv01 2020,Ivica Zubac,2017,2022,7-0,240.0,22.0,LAC,NBA,C,...,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,zubaciv01,2020
24690,zubaciv01 2021,Ivica Zubac,2017,2022,7-0,240.0,23.0,LAC,NBA,C,...,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,zubaciv01,2021
24691,zubaciv01 2022,Ivica Zubac,2017,2022,7-0,240.0,24.0,LAC,NBA,C,...,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6,zubaciv01,2022

In [142]:
cols = df.columns.tolist()
cols = [cols[-2]] + cols[0:6] + [cols[-1]] + cols[6:-2]
df = df[cols]
df

,id,Name,From,To,Height,Weight,Age,Year,Tm,Lg,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,22.0,1969,TOT,NBA,...,0.619,NaN,NaN,8.3,0.8,NaN,NaN,NaN,2.3,7.3
1,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,23.0,1970,MIL,NBA,...,0.643,NaN,NaN,7.5,0.8,NaN,NaN,NaN,2.1,7.4
2,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,24.0,1971,SEA,NBA,...,0.739,NaN,NaN,7.7,0.7,NaN,NaN,NaN,1.9,10.9
3,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,25.0,1972,SEA,NBA,...,0.720,NaN,NaN,11.3,2.1,NaN,NaN,NaN,3.1,13.8
4,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,26.0,1973,HOU,NBA,...,0.735,NaN,NaN,6.3,1.1,NaN,NaN,NaN,2.3,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24687,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,20.0,2018,LAL,NBA,...,0.765,1.0,1.8,2.9,0.6,0.2,0.3,0.6,1.1,3.7
24688,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,21.0,2019,TOT,NBA,...,0.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
24689,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,22.0,2020,LAC,NBA,...,0.747,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3
24690,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,23.0,2021,LAC,NBA,...,0.789,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0
24691,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,24.0,2022,LAC,NBA,...,0.735,2.6,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6

In [143]:
df = df[df['Lg'] == 'NBA']
df

,id,Name,From,To,Height,Weight,Age,Year,Tm,Lg,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,22.0,1969,TOT,NBA,...,0.619,NaN,NaN,8.3,0.8,NaN,NaN,NaN,2.3,7.3
1,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,23.0,1970,MIL,NBA,...,0.643,NaN,NaN,7.5,0.8,NaN,NaN,NaN,2.1,7.4
2,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,24.0,1971,SEA,NBA,...,0.739,NaN,NaN,7.7,0.7,NaN,NaN,NaN,1.9,10.9
3,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,25.0,1972,SEA,NBA,...,0.720,NaN,NaN,11.3,2.1,NaN,NaN,NaN,3.1,13.8
4,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,26.0,1973,HOU,NBA,...,0.735,NaN,NaN,6.3,1.1,NaN,NaN,NaN,2.3,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24687,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,20.0,2018,LAL,NBA,...,0.765,1.0,1.8,2.9,0.6,0.2,0.3,0.6,1.1,3.7
24688,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,21.0,2019,TOT,NBA,...,0.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
24689,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,22.0,2020,LAC,NBA,...,0.747,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3
24690,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,23.0,2021,LAC,NBA,...,0.789,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0
24691,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,24.0,2022,LAC,NBA,...,0.735,2.6,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6

In [145]:
# keep only years above 1978
df['Year'] = df['Year'].apply(pd.to_numeric)
df = df[df['Year'] >= 1978]
df

C:\Users\Daniel\AppData\Local\Temp\ipykernel_8276\4115557082.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Year'].apply(pd.to_numeric)

,id,Name,From,To,Height,Weight,Age,Year,Tm,Lg,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
9,abdulza01,Zaid Abdul-Aziz,1969,1978,6-9,235.0,31.0,1978,TOT,NBA,...,0.739,1.2,1.9,3.1,0.6,0.2,0.2,0.9,1.8,3.9
12,abernto01,Tom Abernethy,1977,1981,6-7,220.0,23.0,1978,LAL,NBA,...,0.820,1.4,2.2,3.6,1.4,0.8,0.3,0.7,1.7,6.8
13,abernto01,Tom Abernethy,1977,1981,6-7,220.0,24.0,1979,GSW,NBA,...,0.745,1.1,2.0,3.1,1.1,0.6,0.2,0.5,1.9,6.0
14,abernto01,Tom Abernethy,1977,1981,6-7,220.0,25.0,1980,GSW,NBA,...,0.683,0.9,1.9,2.9,1.3,0.5,0.2,0.6,1.8,5.4
15,abernto01,Tom Abernethy,1977,1981,6-7,220.0,26.0,1981,TOT,NBA,...,0.591,0.5,0.7,1.2,0.5,0.2,0.1,0.2,0.9,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24687,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,20.0,2018,LAL,NBA,...,0.765,1.0,1.8,2.9,0.6,0.2,0.3,0.6,1.1,3.7
24688,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,21.0,2019,TOT,NBA,...,0.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
24689,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,22.0,2020,LAC,NBA,...,0.747,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3
24690,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,23.0,2021,LAC,NBA,...,0.789,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0
24691,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,24.0,2022,LAC,NBA,...,0.735,2.6,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6

In [146]:
df_teams = pd.read_csv('Teams_prep.csv')
def get_win_rate(data):
    flag = data['Tm']
    year = data['Year']
    win_rate = df_teams[(df_teams['Tm'] == flag) & (df_teams['Year'] == year)].iloc[0]['WR']
    return win_rate

df['G'] = df['G'].apply(pd.to_numeric)
df['TmWin%'] = df[["Tm", "Year"]].apply(get_win_rate, axis=1)

# keep only win rate above 48
df = df[df['TmWin%'] >= 48]

# keep only years with 40 or more games
df = df[df['G'] >= 40]
df

,id,Name,From,To,Height,Weight,Age,Year,Tm,Lg,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,TmWin%
12,abernto01,Tom Abernethy,1977,1981,6-7,220.0,23.0,1978,LAL,NBA,...,1.4,2.2,3.6,1.4,0.8,0.3,0.7,1.7,6.8,54.9
19,abdulma02,Mahmoud Abdul-Rauf,1991,2001,6-1,162.0,24.0,1994,DEN,NBA,...,0.3,1.8,2.1,4.5,1.0,0.1,1.9,1.9,18.0,51.2
20,abdulma02,Mahmoud Abdul-Rauf,1991,2001,6-1,162.0,25.0,1995,DEN,NBA,...,0.4,1.4,1.9,3.6,1.1,0.1,1.6,1.7,16.0,50.0
25,abdelal01,Alaa Abdelnaby,1991,1995,6-10,240.0,22.0,1991,POR,NBA,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,76.8
26,abdelal01,Alaa Abdelnaby,1991,1995,6-10,240.0,23.0,1992,POR,NBA,...,1.1,2.5,3.7,0.4,0.4,0.2,0.9,1.9,6.1,69.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24678,zipsepa01,Paul Zipser,2017,2018,6-8,215.0,22.0,2017,CHI,NBA,...,0.3,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5,50.0
24688,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,21.0,2019,TOT,NBA,...,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,48.0
24689,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,22.0,2020,LAC,NBA,...,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,68.1
24690,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,23.0,2021,LAC,NBA,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,65.3
24691,zubaciv01,Ivica Zubac,2017,2022,7-0,240.0,24.0,2022,LAC,NBA,...,2.6,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6,49.1

In [147]:
def lbs_to_kg(weight):
    if weight is not None and weight != "":
        return 0.45359237 * weight

def feet_to_cm(height):
    if height is not None and height != "":
        feet, inches = height.split("-")
        return 30.48 * float(feet) + 2.54 * float(inches)

df['Height'] = df['Height'].apply(feet_to_cm)
df['Weight'] = df['Weight'].apply(lbs_to_kg)
df

,id,Name,From,To,Height,Weight,Age,Year,Tm,Lg,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,TmWin%
12,abernto01,Tom Abernethy,1977,1981,200.66,99.790321,23.0,1978,LAL,NBA,...,1.4,2.2,3.6,1.4,0.8,0.3,0.7,1.7,6.8,54.9
19,abdulma02,Mahmoud Abdul-Rauf,1991,2001,185.42,73.481964,24.0,1994,DEN,NBA,...,0.3,1.8,2.1,4.5,1.0,0.1,1.9,1.9,18.0,51.2
20,abdulma02,Mahmoud Abdul-Rauf,1991,2001,185.42,73.481964,25.0,1995,DEN,NBA,...,0.4,1.4,1.9,3.6,1.1,0.1,1.6,1.7,16.0,50.0
25,abdelal01,Alaa Abdelnaby,1991,1995,208.28,108.862169,22.0,1991,POR,NBA,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,76.8
26,abdelal01,Alaa Abdelnaby,1991,1995,208.28,108.862169,23.0,1992,POR,NBA,...,1.1,2.5,3.7,0.4,0.4,0.2,0.9,1.9,6.1,69.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24678,zipsepa01,Paul Zipser,2017,2018,203.20,97.522360,22.0,2017,CHI,NBA,...,0.3,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5,50.0
24688,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,21.0,2019,TOT,NBA,...,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,48.0
24689,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,22.0,2020,LAC,NBA,...,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,68.1
24690,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,23.0,2021,LAC,NBA,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,65.3
24691,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,24.0,2022,LAC,NBA,...,2.6,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6,49.1

In [148]:
cols_to_convert = [
        "From", "To", "Height", "Weight", "Age", "GS", "MP", "FG", "FGA", "FG%", "3P", "3PA", "3P%", "2P",
        "2PA", "2P%", "eFG%", "FT", "FTA", "FT%", "ORB", "DRB", "TRB", "AST", "STL", "BLK", "TOV", "PF", "PTS"
    ]
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_numeric)
df

,id,Name,From,To,Height,Weight,Age,Year,Tm,Lg,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,TmWin%
12,abernto01,Tom Abernethy,1977,1981,200.66,99.790321,23.0,1978,LAL,NBA,...,1.4,2.2,3.6,1.4,0.8,0.3,0.7,1.7,6.8,54.9
19,abdulma02,Mahmoud Abdul-Rauf,1991,2001,185.42,73.481964,24.0,1994,DEN,NBA,...,0.3,1.8,2.1,4.5,1.0,0.1,1.9,1.9,18.0,51.2
20,abdulma02,Mahmoud Abdul-Rauf,1991,2001,185.42,73.481964,25.0,1995,DEN,NBA,...,0.4,1.4,1.9,3.6,1.1,0.1,1.6,1.7,16.0,50.0
25,abdelal01,Alaa Abdelnaby,1991,1995,208.28,108.862169,22.0,1991,POR,NBA,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,76.8
26,abdelal01,Alaa Abdelnaby,1991,1995,208.28,108.862169,23.0,1992,POR,NBA,...,1.1,2.5,3.7,0.4,0.4,0.2,0.9,1.9,6.1,69.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24678,zipsepa01,Paul Zipser,2017,2018,203.20,97.522360,22.0,2017,CHI,NBA,...,0.3,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5,50.0
24688,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,21.0,2019,TOT,NBA,...,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,48.0
24689,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,22.0,2020,LAC,NBA,...,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,68.1
24690,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,23.0,2021,LAC,NBA,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,65.3
24691,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,24.0,2022,LAC,NBA,...,2.6,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6,49.1

In [153]:
# fill 2P nulls with FG
df['2P'].fillna(df['FG'], inplace=True)
df['2PA'].fillna(df['FGA'], inplace=True)
df['2P%'].fillna(df['FG%'], inplace=True)

# fill other nulls with 0
df.fillna(0, inplace=True)
df

,id,Name,From,To,Height,Weight,Age,Year,Tm,Lg,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,TmWin%,score2
12,abernto01,Tom Abernethy,1977,1981,200.66,99.790321,23.0,1978,LAL,NBA,...,2.2,3.6,1.4,0.8,0.3,0.7,1.7,6.8,54.9,0.000000
19,abdulma02,Mahmoud Abdul-Rauf,1991,2001,185.42,73.481964,24.0,1994,DEN,NBA,...,1.8,2.1,4.5,1.0,0.1,1.9,1.9,18.0,51.2,14.624502
20,abdulma02,Mahmoud Abdul-Rauf,1991,2001,185.42,73.481964,25.0,1995,DEN,NBA,...,1.4,1.9,3.6,1.1,0.1,1.6,1.7,16.0,50.0,12.411367
25,abdelal01,Alaa Abdelnaby,1991,1995,208.28,108.862169,22.0,1991,POR,NBA,...,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,76.8,0.000000
26,abdelal01,Alaa Abdelnaby,1991,1995,208.28,108.862169,23.0,1992,POR,NBA,...,2.5,3.7,0.4,0.4,0.2,0.9,1.9,6.1,69.5,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24678,zipsepa01,Paul Zipser,2017,2018,203.20,97.522360,22.0,2017,CHI,NBA,...,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5,50.0,4.035308
24688,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,21.0,2019,TOT,NBA,...,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,48.0,0.000000
24689,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,22.0,2020,LAC,NBA,...,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,68.1,9.000768
24690,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,23.0,2021,LAC,NBA,...,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,65.3,9.902620
24691,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,24.0,2022,LAC,NBA,...,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6,49.1,0.000000

In [154]:
from formula import calc_score

# add score according to the formula
df['score2'] = df.apply(calc_score, axis=1)

In [155]:
df

,id,Name,From,To,Height,Weight,Age,Year,Tm,Lg,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,TmWin%,score2
12,abernto01,Tom Abernethy,1977,1981,200.66,99.790321,23.0,1978,LAL,NBA,...,2.2,3.6,1.4,0.8,0.3,0.7,1.7,6.8,54.9,6.643703
19,abdulma02,Mahmoud Abdul-Rauf,1991,2001,185.42,73.481964,24.0,1994,DEN,NBA,...,1.8,2.1,4.5,1.0,0.1,1.9,1.9,18.0,51.2,14.624502
20,abdulma02,Mahmoud Abdul-Rauf,1991,2001,185.42,73.481964,25.0,1995,DEN,NBA,...,1.4,1.9,3.6,1.1,0.1,1.6,1.7,16.0,50.0,12.411367
25,abdelal01,Alaa Abdelnaby,1991,1995,208.28,108.862169,22.0,1991,POR,NBA,...,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,76.8,2.651714
26,abdelal01,Alaa Abdelnaby,1991,1995,208.28,108.862169,23.0,1992,POR,NBA,...,2.5,3.7,0.4,0.4,0.2,0.9,1.9,6.1,69.5,4.851042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24678,zipsepa01,Paul Zipser,2017,2018,203.20,97.522360,22.0,2017,CHI,NBA,...,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5,50.0,4.035308
24688,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,21.0,2019,TOT,NBA,...,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,48.0,8.333180
24689,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,22.0,2020,LAC,NBA,...,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,68.1,9.000768
24690,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,23.0,2021,LAC,NBA,...,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,65.3,9.902620
24691,zubaciv01,Ivica Zubac,2017,2022,213.36,108.862169,24.0,2022,LAC,NBA,...,5.4,8.0,1.3,0.5,1.0,1.4,2.5,9.6,49.1,10.403375